### ISSUE TITLE
Working Sample

### ISSUE THREAD

**Issue by coreyperkins** [jaredhanson/passport-openidconnect#5]
This is a question. Does anybody have a working sample of using this? I have a openid connect auth server in place using another tech and I'd like to use this lib to connect to it with an outside nodejs app. A sample would be handy. Thanks!

**Comment by gobengo** [comment]
+1

**Comment by jasps** [comment]
I got it to work after a few tweaks, what are you having an issue with specifically?

**Comment by coreyperkins** [comment]
The only issue is myself. :) 

I haven't used passport much and I was hoping for a quick and dirty I could slap into place to give it a shot. I thought it might be something that could benefit others as well.

Thanks!

**Comment by jasps** [comment]
Check out the examples for passport-local (https://github.com/jaredhanson/passport-local) and then it should just be case of changing the options for your strategy.  The thing I had an issue with was the call to self._verify in the getOAuthAccessToken function of the strategy. Make sure this aligned with your passport.use callback in your app.

**Comment by coreyperkins** [comment]
Interesting, I will check them out. Much appreciated.

**Comment by coreyperkins** [comment]
I'm struggling with this quite a bit. I've nabbed the passport-local example and I've started going through it but there are some basics I don't understand. 

var OidcStrategy = require('passport-openidconnect').Strategy;

I've setup the strategy in passport by doing the following.

passport.use(new OidcStrategy({
  authorizationURL: 'my-auth-endpoint',
  tokenURL: 'my-token-endpoint',
  userInfoURL: 'my-user-info-endpoint',
  clientID: 'my-client',
  clientSecret: 'my-client-secret',
  callbackURL: '/callback'
}, verify));

I think this chunk needs to be modified to go out to the openid connect server I am trying to use for auth.

app.get('/login', 
  passport.authenticate('local', { failureRedirect: '/login', failureFlash: true }),
  function(req, res) {
    res.redirect('/');
  });

At this point, I am not quite sure how to modify this to properly interact with passport-openidconnect. I am getting confused at the point of calling the authenticate middleware.

I thought maybe I could simply call authenticate and it would attempt to hit my auth endpoint. Perhaps like this.

app.get('/login', 
  passport.authenticate()
);

This is resulting in a 401 without even trying to go out to the auth endpoint I specified.

Any advice?

**Comment by jasps** [comment]
In this snippet of code:

app.get('/login', 
passport.authenticate('local', { failureRedirect: '/login', failureFlash: true }),
function(req, res) {
res.redirect('/');
});

passport.authenticate('local'... should be passport.authenticate('passport-openidconnect'...

**Comment by coreyperkins** [comment]
I think I'm still missing something fundamental. Here's my script.

var OidcStrategy = require('passport-openidconnect').Strategy;

passport.use(new OidcStrategy({
  authorizationURL: baseAuthUrl + '/id/conn/auth',
  tokenURL: baseAuthUrl + '/id/conn/token',
  userInfoURL: baseAuthUrl + '/id/conn/userinfo',
  clientID: 'fakeClient',
  clientSecret: 'fakeSecret',
  callbackURL: '/authorize'
});

app.get('/login', 
  passport.authenticate('passport-openidconnect', { failureRedirect: '/login', failureFlash: true }),
  function(req, res) {
    console.log('verify hit');

    res.redirect('/');
});

When I hit /login it will tell me this:

Error: Unknown authentication strategy "passport-openidconnect"
   at attempt (C:\nodeoidc\node_modules\passport\lib\middleware\authenticate.js:166:37)
   at authenticate (C:\nodeoidc\node_modules\passport\lib\middleware\authenticate.js:342:7)
   at Layer.handle [as handle_request] (C:\nodeoidc\node_modules\express\lib\router\layer.js:82:5)
   at next (C:\nodeoidc\node_modules\express\lib\router\route.js:110:13)
   at Route.dispatch (C:\nodeoidc\node_modules\express\lib\router\route.js:91:3)
   at Layer.handle [as handle_request] (C:\nodeoidc\node_modules\express\lib\router\layer.js:82:5)
   at C:\nodeoidc\node_modules\express\lib\router\index.js:267:22
   at Function.proto.process_params (C:\nodeoidc\node_modules\express\lib\router\index.js:321:12)
   at next (C:\nodeoidc\node_modules\express\lib\router\index.js:261:10)
   at SendStream.error (C:\nodeoidc\node_modules\express\node_modules\serve-static\index.js:107:7)

**Comment by jasps** [comment]
Corey,

Try this (changing passport-openidconnect to openidconnect):

app.get('/login', 
passport.authenticate('openidconnect', { failureRedirect: '/login', failureFlash: true }),
function(req, res) {
console.log('verify hit');
res.redirect('/');
});

**Comment by coreyperkins** [comment]
That did it! I was redirected to my auth server which reported an invalid response because I don't yet have "code" allowed as a response type. 

It looks like "code" is hard-coded into the source, know if there are any plans to support other response types?

**Comment by jasps** [comment]
Good news. Just create your own local module and base it on passport-openidconnect then you can change it to whatever you like. Check the openid-connect specs for the different flows.

**Comment by juanifioren** [comment]
@coreyperkins @jasps 
When you write:
```javascript
passport.use(new OidcStrategy({
    authorizationURL: 'my-auth-endpoint',
    tokenURL: 'my-token-endpoint',
    userInfoURL: 'my-user-info-endpoint',
    clientID: 'my-client',
    clientSecret: 'my-client-secret',
    callbackURL: '/callback'
}, verify));
```
Whay exactly is that function `verify`? If I don't pass it as a parameter then I got an error.

**Comment by jasps** [comment]
This is the function that will capture your profile, claims etc.  You need it. In this function, you will usually pull the relevant user from a database and return that user or a sub-set of user attributes, which is what I do.  This is what passport will serialize in the session.

**Comment by juanifioren** [comment]
Thanks @jasps for that fast reply. I understand now. Do u have a working example of this function?.

**Comment by jasps** [comment]
Not that would help you I'm afraid. Check the samples. There is one that pulls a user from MongoDB.

**Comment by juanifioren** [comment]
Thanks anyways man! @jasps 
I ended up with this function, it works.

```javascript
function (iss, sub, profile, done) {
  User.find({ email: profile._json.email }, function (err, docs) {
    if (docs.length == 0) {
      var user = new User({ email: profile._json.email });
      user.save();
      return done(err, user);
    } else {
      return done(err, docs[0]);
    }
  });
}
```
Tested against [django-oidc-provider](https://github.com/juanifioren/django-oidc-provider).

**Comment by mithun-daa** [comment]
@jasps What did you do to fix the verify callback?
> The thing I had an issue with was the call to self._verify in the getOAuthAccessToken function of the strategy. Make sure this aligned with your passport.use callback in your app.

My verify callback is not getting called either.

**Comment by whindes** [comment]
Is there any update or workaround for the response_type?  It is still hard coded to "code" and it would be nice to have "id_token token".  Please let us know of any alternate solutions.

**Comment by mithun-daa** [comment]
@whindes I used https://github.com/panva/node-openid-client for that and it works great.

**Comment by barnaby33** [comment]
Got a code snippet for using the token/implicit flow?

**Comment by Harshil1989** [comment]
I am trying to integrate this with my sample node js project...but I am not able to understand how to invoke this...since  I am getting the below error when I call this:

TypeError: Parameter "url" must be a string, not undefined (at the below line in the strategy.js of this lib)
this._key = options.sessionKey || (this.name + ':' + url.parse(options.authorizationURL).hostname);

I am passing all these parameters:
  authorizationURL: 'my-auth-endpoint',
    tokenURL: 'my-token-endpoint',
    userInfoURL: 'my-user-info-endpoint',
    clientID: 'my-client',
    clientSecret: 'my-client-secret',
    callbackURL: '/callback'

can someone let me know...what I am doing wrong?
Any help appreciated...Thanks!

**Comment by barnaby33** [comment]
First guess is that the values you are passing are 'my-auth-endpoint' instead of the URL to your OAuth/OpenId server.

**Comment by Harshil1989** [comment]
@barnaby33 I think it is expecting a parameter "url" from the request....atleast that's what I am interpreting from the error message...my question is do we have to pass any other parameter apart from the ones I have mentioned below...or I guess I may be doing it all wrong...
This is the configuration of passport that I am setting:

  openidconnect: {
       name: 'openidconnect',
       protocol: 'openid',
       scope: [ 'openid profile' ],
       options: {
        authorizationURL: 'my-auth-endpoint',
        tokenURL: 'my-token-endpoint',
        userInfoURL: 'my-user-info-endpoint',
       clientID: 'my-client',
       clientSecret: 'my-client-secret',
       callbackURL: '/callback'
       }
  }
Any help appreciated...Thanks!

**Comment by Harshil1989** [comment]
Finally got it working...
Just one question though...has anyone faced the issue related to CORS ???
I am trying to make a cross-domain request and apparently the browser is making a Pre-flight request with method type "OPTIONS" before making the actual request.
Since the server is not supporting this method typ,, I am getting an error method not allowed error in the response due to which I am not able to complete the transaction...
I also went through the specs of CORS request...and found that if any custom header is added in the cross-origin request then the browser will automatically make a Pre-flight request to check if it has permission to perform the task...
I wonder if there is way to configure this lib to disable Pre-flight request (I highly doubt if this is possible since it is the browser that does this)...
Does anyone have any idea if there is any configuration settings that would remove the additional headers or only way to do this is to fork this lib and make the modifications in the lib itself ?

Any help appreciated...Thanks!

**Comment by fdescamps** [comment]
@barnaby33 : did you find a code snippet for using the token/implicit flow?

**Comment by barnaby33** [comment]
Actually I don't remember. This was almost a year ago for me. I believe I did or rather pieced one together, but don't have a link.               Josh
    On Tuesday, January 2, 2018, 3:57:59 AM PST, François <notifications@github.com> wrote:  
 
 
@barnaby33 : did you find a code snippet for using the token/implicit flow?
