### ISSUE TITLE
Support of PKCE workflow

### ISSUE THREAD

**Issue by mliu0506** [jaredhanson/passport-openidconnect#83]
Some OpenId Connect based Server Support the PKCE workflow according to [https://tools.ietf.org/html/rfc7636#page-8].
Your package is pretty much there in supporting this workflow by defining the necessary additional parameters like e.g. nonce, code_challenge, code_challenge_method using the authorizationParams function. However, I haven't seen an option to extend the authentication request by similar means, e.g. with the necessary parameter code_verifier.
Did I miss something? If not it would be great you could add a similar mechanism like the authorizationParams to the authentication request

Here is my detail error message:
AuthorizationError: Missing parameter, 'code_challenge'

    at Strategy.authenticate (/Users/michael/Desktop/working/Gitlab/covid-more/node_modules/passport-openidconnect/lib/strategy.js:79:25)
    at attempt (/Users/michael/Desktop/working/Gitlab/covid-more/node_modules/passport/lib/middleware/authenticate.js:367:16)
    at authenticate (/Users/michael/Desktop/working/Gitlab/covid-more/node_modules/passport/lib/middleware/authenticate.js:368:7)
    at Layer.handle [as handle_request] (/Users/michael/Desktop/working/Gitlab/covid-more/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/michael/Desktop/working/Gitlab/covid-more/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/michael/Desktop/working/Gitlab/covid-more/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/michael/Desktop/working/Gitlab/covid-more/node_modules/express/lib/router/layer.js:95:5)
    at /Users/michael/Desktop/working/Gitlab/covid-more/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/michael/Desktop/working/Gitlab/covid-more/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/michael/Desktop/working/Gitlab/covid-more/node_modules/express/lib/router/index.js:275:10) {
  code: 'invalid_request',
  uri: undefined,
  status: 500
}

**Comment by saidheerajpaluvadi** [comment]
Hi Any update on this ? Is there any alternate npm library to use openidconnect with PKCE supported?
